spring.application.name=instructorapi
spring.data.mongodb.uri=mongodb://myUser:myPassword@localhost:27017/trainingdb?authSource=admin
spring.data.mongodb.auto-index-creation=true

logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=INFO
logging.level.com.example.instructorapi=DEBUG

app.jwt.secret=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
app.jwt.expiration-ms=3600000